create table pizza (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name VARCHAR(64) NOT NULL,
    price DECIMAL(14,2) NOT NULL
);

insert into pizza (name, price) values ('Paulista', 36.00);
insert into pizza (name, price) values ('Mussarela', 32.00);
insert into pizza (name, price) values ('Calabresa', 33.00);
insert into pizza (name, price) values ('Atum', 35.00);
insert into pizza (name, price) values ('Picanha', 50.00);
 
-- creating user and user_authority tables
CREATE TABLE user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    username VARCHAR(64) NOT NULL, 
	password VARCHAR(200) NOT NULL,
	firstname VARCHAR(64) NOT NULL,
	lastname VARCHAR(64) NOT NULL,
	CONSTRAINT uq_user_login UNIQUE (username)
);
  
CREATE TABLE user_authority (
	user_id INTEGER NOT NULL,
	authority_id VARCHAR(64) NOT NULL,
	PRIMARY KEY (user_id, authority_id)
);

CREATE TABLE authority (
    id VARCHAR(64) NOT NULL,
    description VARCHAR(256),
    PRIMARY KEY (id)
);

-- inserindo papeis
insert into authority values ('USER', 'Acesso ao cadastro de pizzas');
insert into authority values ('ADMIN', 'Acesso ao cadastro de usuários');

-- inserindo usuarios
insert into user (username, password, firstname, lastname) values ('willian', '6d3b81630883bc54a92cfea42b1cea1a54e7fce7569a9ebdb94db3953e08705ca45db1a3f49afedb', 'Willian', 'Fuertes Batista');
insert into user (username, password, firstname, lastname) values ('flavia', '14db4689bd390ba22368cce3f4d3559d23206a9bcf73914fe2ab1724c1e64d96b81130d3c433fe08', 'Flavia', 'Pondian');

-- inserindo papeis ao usuarios
insert into user_authority values ((select id from user where username = 'willian'), 'USER');
insert into user_authority values ((select id from user where username = 'willian'), 'ADMIN');
insert into user_authority values ((select id from user where username = 'flavia'), 'USER');